### ISSUE TITLE
More directives

### ISSUE THREAD

**Issue by m1guelpf** [appstract/laravel-blade-directives#13]
I have a few directives I created for my projects, and I thought you could be interested in adding some to this package:

- Repeat and EndRepeat: A for loop that repeats the contents the number of times specified. Example: 
``` php
@repeat(3)
Test
@endrepeat
```

- Production: A custom IF directive that only runs when in production
- Local: Same as  above but for local enviroment

**Comment by gizburdt** [comment]
We like the repeat directive. Can you create a PR for that one?
