### ISSUE TITLE
@fa directive

### ISSUE THREAD

**Issue by danielmarkavis** [appstract/laravel-blade-directives#20]
Could we include a param in this to add more classes, "fa-lg" for example.

@fa('address-book', 'fa-lg')

**Comment by gizburdt** [comment]
Cool idea! Can you provide us with a PR?

**Comment by aziev** [comment]
Hey guys, could you check it: #21

**Comment by danielmarkavis** [comment]
That looks like it should do it.

**Comment by gizburdt** [comment]
Thanks guys! :)
