### ISSUE TITLE
@fa including a comma in the class second param

### ISSUE THREAD

**Issue by danielmarkavis** [appstract/laravel-blade-directives#22]
@fa('facebook', 'fa-spin') 

gives 

<i class="fa fa-facebook, fa-spin" aria-hidden="true"></i>

adding a comma after "fa-facebook".

**Comment by teuunn** [comment]
@danielmarkavis sure you've pulled in [latest release](https://github.com/appstract/laravel-blade-directives/releases/tag/0.5.2) (published 2 hours ago)? I cannot reproduce.

**Comment by gizburdt** [comment]
Should be fixed in 0.5.2. Please run composer update :)

**Comment by danielmarkavis** [comment]
Ah yes I was doing this

@fa('facebook', 'fa-spin')

but this works

@fa('facebook, fa-spin')

**Comment by gizburdt** [comment]
This should work: @fa('facebook', 'fa-spin')

Just update to the newest version :)

**Comment by danielmarkavis** [comment]
Yes it does now, I think I had some caching issues.
