### ISSUE TITLE
Directive @fa with FontAwsome 5.x

### ISSUE THREAD

**Issue by innovaweb-dev** [appstract/laravel-blade-directives#37]
Hi,

Thank you for this good repository.
Just for your information, since Font Awesome 5.x, the syntax have changed.
For example:

```php
// FontAwesome 5.x
<i class="fas fa-user"></i>

// @fa('user') don't working
<i class="fa fa-user"></i>

// @fa('user', 'fas') working with FontAwesome 5.x
// But it's not correct syntax
<i class="fa fa-user fas"></i>
```

Because since 5.x, we have three icon styles.

- fas : for solid icons
- far : for regular icons
- fab : for brands's icon

**Comment by ovanschie** [comment]
And also Light...

I think best approach is to create separate directives (```@fas, @far, @fal, @fab```).
