### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by nalletje** [appstract/laravel-blade-directives#70]
Is there going to be an small update for laravel 10 ?

**Comment by gizburdt** [comment]
If you create a PR, we will merge it :)

**Comment by roopajoshyam** [comment]
Any update for Laravel 10?

**Comment by nalletje** [comment]
> Any update for Laravel 10?

We didn't create an PR, we decided to drop the package, since the directives we use can we replaced by default laravel 10 directives (like pushonce)
